spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://127.0.0.1:5432/

management:
  endpoints:
    web:
      exposure:
        include: "info"
